version: '3.8'

services:
  jenkins:
    image: jenkins-devops-docker:latest
    container_name: jenkins-devops
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    networks:
      - devops-network

  tomcat:
    image: tomcat:10.1-jdk17
    container_name: tomcat-staging
    ports:
      - "8082:8080"
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps
    restart: unless-stopped
    networks:
      - devops-network

volumes:
  jenkins_home:
  tomcat_webapps:

networks:
  devops-network:
    driver: bridge
